Worked on WealthStream. Created branch "docker" to move all services into a Docker container. Had issues with frontend service failing to start. **NB: Cline decided to rename env variables from PUBLIC_ to VITE_** have seen issues with this before, and if things stop working this is somewhere to look. 

Cline moved back to PUBLIC_ vars, and we created a local .env file. 

Still having issues with CORS. Make sure it doesn't go around in circles, and check the output in F12 in the browser when you see "NetworkError when attempting to fetch resource".

CORS fixed. Now getting authentication error:
 2025-01-14 14:30:38 - werkzeug - INFO - 192.168.4.46 - - [14/Jan/2025 14:30:38] "POST /auth/login HTTP/1.1" 500 -
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.hooks - DEBUG - Event before-parameter-build.cognito-identity-provider.InitiateAuth: calling handler <function generate_idempotent_uuid at 0x75a701d79f80>
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.regions - DEBUG - Calling endpoint provider with parameters: {'Region': 'eu-west-2', 'UseDualStack': False, 'UseFIPS': False}
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.regions - DEBUG - Endpoint provider result: https://cognito-idp.eu-west-2.amazonaws.com
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.hooks - DEBUG - Event before-call.cognito-identity-provider.InitiateAuth: calling handler <function add_recursion_detection_header at 0x75a701d787c0>
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.hooks - DEBUG - Event before-call.cognito-identity-provider.InitiateAuth: calling handler <function add_query_compatibility_header at 0x75a701da0a40>
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.hooks - DEBUG - Event before-call.cognito-identity-provider.InitiateAuth: calling handler <function inject_api_version_header_if_needed at 0x75a701d7ba60>
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.endpoint - DEBUG - Making request for OperationModel(name=InitiateAuth) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'X-Amz-Target': 'AWSCognitoIdentityProviderService.InitiateAuth', 'Content-Type': 'application/x-amz-json-1.1', 'User-Agent': 'Boto3/1.35.98 md/Botocore#1.35.98 ua/2.0 os/linux#6.8.0-51-generic md/arch#x86_64 lang/python#3.11.11 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.35.98'}, 'body': b'{"ClientId": "3p6uh4nhlrqb7guudfitfqkptv", "AuthFlow": "USER_PASSWORD_AUTH", "AuthParameters": {"USERNAME": "mike@griggs.org.uk", "PASSWORD": "Wealth123!", "SECRET_HASH": "rEsPjLVQNbZ/JPAi78GlV6toO0Fc9IxAUmvepkeuwjQ="}}', 'url': 'https://cognito-idp.eu-west-2.amazonaws.com/', 'context': {'client_region': 'eu-west-2', 'client_config': <botocore.config.Config object at 0x75a700f143d0>, 'has_streaming_input': False, 'auth_type': 'none', 'unsigned_payload': None}}
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.hooks - DEBUG - Event request-created.cognito-identity-provider.InitiateAuth: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x75a700f14390>>
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.hooks - DEBUG - Event choose-signer.cognito-identity-provider.InitiateAuth: calling handler <function set_operation_specific_signer at 0x75a701d79da0>
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.hooks - DEBUG - Event request-created.cognito-identity-provider.InitiateAuth: calling handler <function add_retry_headers at 0x75a701da02c0>
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://cognito-idp.eu-west-2.amazonaws.com/, headers={'X-Amz-Target': b'AWSCognitoIdentityProviderService.InitiateAuth', 'Content-Type': b'application/x-amz-json-1.1', 'User-Agent': b'Boto3/1.35.98 md/Botocore#1.35.98 ua/2.0 os/linux#6.8.0-51-generic md/arch#x86_64 lang/python#3.11.11 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.35.98', 'amz-sdk-invocation-id': b'9af3a5a9-ba1d-414e-b4b7-87e74f4b5a6d', 'amz-sdk-request': b'attempt=1', 'Content-Length': '219'}>
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.httpsession - DEBUG - Certificate path: /opt/venv/lib/python3.11/site-packages/certifi/cacert.pem
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - urllib3.connectionpool - DEBUG - https://cognito-idp.eu-west-2.amazonaws.com:443 "POST / HTTP/1.1" 400 110
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.parsers - DEBUG - Response headers: {'Date': 'Tue, 14 Jan 2025 14:31:26 GMT', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '110', 'Connection': 'keep-alive', 'x-amzn-RequestId': '0a1180e5-6ccb-4adb-9852-6b59cb86fd31', 'x-amzn-ErrorType': 'ResourceNotFoundException:', 'x-amzn-ErrorMessage': 'User pool client 3p6uh4nhlrqb7guudfitfqkptv does not exist.'}
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.parsers - DEBUG - Response body:
wealthstream-portfolio-1  | b'{"__type":"ResourceNotFoundException","message":"User pool client 3p6uh4nhlrqb7guudfitfqkptv does not exist."}'
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.parsers - DEBUG - Response headers: {'Date': 'Tue, 14 Jan 2025 14:31:26 GMT', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '110', 'Connection': 'keep-alive', 'x-amzn-RequestId': '0a1180e5-6ccb-4adb-9852-6b59cb86fd31', 'x-amzn-ErrorType': 'ResourceNotFoundException:', 'x-amzn-ErrorMessage': 'User pool client 3p6uh4nhlrqb7guudfitfqkptv does not exist.'}
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.parsers - DEBUG - Response body:
wealthstream-portfolio-1  | b'{"__type":"ResourceNotFoundException","message":"User pool client 3p6uh4nhlrqb7guudfitfqkptv does not exist."}'
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.hooks - DEBUG - Event needs-retry.cognito-identity-provider.InitiateAuth: calling handler <botocore.retryhandler.RetryHandler object at 0x75a700bfd490>
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - botocore.retryhandler - DEBUG - No retry needed.
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - wealthstream.portfolio_service.handlers.user_handlers - ERROR - Authentication error: An error occurred (ResourceNotFoundException) when calling the InitiateAuth operation: User pool client 3p6uh4nhlrqb7guudfitfqkptv does not exist.
wealthstream-portfolio-1  | 2025-01-14 14:31:26 - __main__ - INFO - Request headers: Host: wealthstream-app-server.corp.griggs.org.uk:8001
wealthstream-portfolio-1  | User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0

Might be to do with the hostname changes? Need to login to AWS and check.


